#pragma once
#include "Aplicatie.h"
#include "RepositorySTL.h"
#include "RepoFile.h"
#include "Service.h"
void appTests();
void repositorySTLTests();
void serviceTests();
void testeRepoFile();
